import { spawn, ChildProcess } from 'child_process';
import { EventEmitter } from 'events';
import path from 'path';
import fs from 'fs';
import os from 'os';
import { createLogger } from '../utils/logger.js';

const logger = createLogger('go2rtc');

export interface Go2RTCConfig {
  enabled: boolean;
  apiPort: number;
  webrtcPort: number;
  binaryPath?: string;
  stunServers: string[];
}

export interface StreamInfo {
  name: string;
  url: string;
  consumers: number;
}

export interface Go2RTCServiceEvents {
  'started': () => void;
  'stopped': () => void;
  'error': (error: Error) => void;
  'stream:added': (streamId: string) => void;
  'stream:removed': (streamId: string) => void;
}

export class Go2RTCService extends EventEmitter {
  private config: Go2RTCConfig;
  private process: ChildProcess | null = null;
  private configPath: string;
  private streams: Map<string, string> = new Map(); // streamId -> sourceUrl

  constructor(config: Go2RTCConfig) {
    super();
    this.config = config;
    this.configPath = path.join(os.tmpdir(), 'go2rtc-cira.yaml');
  }

  // Get the path to the go2rtc binary based on platform
  private getBinaryPath(): string {
    if (this.config.binaryPath) {
      return this.config.binaryPath;
    }

    const platform = os.platform();
    const binDir = path.join(process.cwd(), 'bin');

    switch (platform) {
      case 'win32':
        return path.join(binDir, 'go2rtc-windows-amd64.exe');
      case 'darwin':
        return path.join(binDir, 'go2rtc-darwin-amd64');
      case 'linux':
        return path.join(binDir, 'go2rtc-linux-amd64');
      default:
        throw new Error(`Unsupported platform: ${platform}`);
    }
  }

  // Generate go2rtc YAML configuration
  private generateConfig(): string {
    const streamsObj: Record<string, string> = {};
    for (const [id, url] of this.streams) {
      streamsObj[id] = url;
    }

    // Build STUN/TURN servers config
    const iceServers = this.config.stunServers.map(s => `- ${s}`).join('\n    ');

    const yaml = `
# Auto-generated by CiRA Edge Gateway
api:
  listen: ":${this.config.apiPort}"
  origin: "*"

ffmpeg:
  bin: ffmpeg

webrtc:
  listen: ":${this.config.webrtcPort}"
  candidates:
    ${iceServers}

streams:
${Object.entries(streamsObj).map(([id, url]) => `  ${id}: ${url}`).join('\n')}
`;

    return yaml.trim();
  }

  // Write configuration file
  private writeConfig(): void {
    const config = this.generateConfig();
    fs.writeFileSync(this.configPath, config, 'utf-8');
    logger.debug(`Wrote go2rtc config to ${this.configPath}`);
  }

  // Start go2rtc process
  async start(): Promise<void> {
    if (!this.config.enabled) {
      logger.info('go2rtc is disabled in configuration');
      return;
    }

    const binaryPath = this.getBinaryPath();

    // Check if binary exists
    if (!fs.existsSync(binaryPath)) {
      throw new Error(`go2rtc binary not found at: ${binaryPath}`);
    }

    // Make binary executable on Unix systems
    if (os.platform() !== 'win32') {
      try {
        fs.chmodSync(binaryPath, 0o755);
      } catch (e) {
        // Ignore chmod errors
      }
    }

    // Write initial config
    this.writeConfig();

    logger.info(`Starting go2rtc from ${binaryPath}`);
    logger.info(`API: http://localhost:${this.config.apiPort}`);
    logger.info(`WebRTC: ws://localhost:${this.config.webrtcPort}`);

    this.process = spawn(binaryPath, ['-config', this.configPath], {
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
    });

    this.process.stdout?.on('data', (data: Buffer) => {
      const lines = data.toString().split('\n').filter(l => l.trim());
      for (const line of lines) {
        logger.debug(`[go2rtc] ${line}`);
      }
    });

    this.process.stderr?.on('data', (data: Buffer) => {
      const lines = data.toString().split('\n').filter(l => l.trim());
      for (const line of lines) {
        logger.warn(`[go2rtc] ${line}`);
      }
    });

    this.process.on('error', (error: Error) => {
      logger.error(`go2rtc process error: ${error.message}`);
      this.emit('error', error);
    });

    this.process.on('exit', (code: number | null, signal: string | null) => {
      logger.info(`go2rtc process exited (code: ${code}, signal: ${signal})`);
      this.process = null;
      this.emit('stopped');
    });

    // Wait for go2rtc to be ready
    await this.waitForReady();
    this.emit('started');
    logger.info('go2rtc started successfully');
  }

  // Wait for go2rtc API to be ready
  private async waitForReady(timeoutMs: number = 10000): Promise<void> {
    const startTime = Date.now();

    while (Date.now() - startTime < timeoutMs) {
      try {
        const response = await fetch(`http://localhost:${this.config.apiPort}/api`);
        if (response.ok) {
          return;
        }
      } catch {
        // Not ready yet
      }
      await new Promise(resolve => setTimeout(resolve, 100));
    }

    throw new Error('go2rtc failed to start within timeout');
  }

  // Stop go2rtc process
  async stop(): Promise<void> {
    if (!this.process) {
      return;
    }

    logger.info('Stopping go2rtc');

    return new Promise((resolve) => {
      if (!this.process) {
        resolve();
        return;
      }

      this.process.once('exit', () => {
        this.process = null;
        resolve();
      });

      // Try graceful shutdown first
      this.process.kill('SIGTERM');

      // Force kill after 5 seconds
      setTimeout(() => {
        if (this.process) {
          this.process.kill('SIGKILL');
        }
      }, 5000);
    });
  }

  // Check if go2rtc is running
  isRunning(): boolean {
    return this.process !== null;
  }

  // Register a stream with go2rtc
  async registerStream(streamId: string, sourceUrl: string): Promise<void> {
    if (!this.isRunning()) {
      logger.warn('Cannot register stream: go2rtc is not running');
      return;
    }

    // Store locally
    this.streams.set(streamId, sourceUrl);

    // Register via go2rtc API
    try {
      const response = await fetch(
        `http://localhost:${this.config.apiPort}/api/streams?src=${encodeURIComponent(sourceUrl)}&name=${encodeURIComponent(streamId)}`,
        { method: 'PUT' }
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      logger.info(`Registered stream: ${streamId} -> ${sourceUrl}`);
      this.emit('stream:added', streamId);
    } catch (error) {
      logger.error(`Failed to register stream ${streamId}: ${error}`);
      throw error;
    }
  }

  // Unregister a stream from go2rtc
  async unregisterStream(streamId: string): Promise<void> {
    if (!this.isRunning()) {
      return;
    }

    this.streams.delete(streamId);

    try {
      const response = await fetch(
        `http://localhost:${this.config.apiPort}/api/streams?name=${encodeURIComponent(streamId)}`,
        { method: 'DELETE' }
      );

      if (!response.ok && response.status !== 404) {
        throw new Error(`HTTP ${response.status}`);
      }

      logger.info(`Unregistered stream: ${streamId}`);
      this.emit('stream:removed', streamId);
    } catch (error) {
      logger.error(`Failed to unregister stream ${streamId}: ${error}`);
    }
  }

  // Get all registered streams
  async getStreams(): Promise<Map<string, StreamInfo>> {
    const result = new Map<string, StreamInfo>();

    if (!this.isRunning()) {
      return result;
    }

    try {
      const response = await fetch(`http://localhost:${this.config.apiPort}/api/streams`);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const data = await response.json() as Record<string, {
        producers?: Array<{ url?: string }>;
        consumers?: number;
      }>;

      for (const [name, info] of Object.entries(data)) {
        result.set(name, {
          name,
          url: info.producers?.[0]?.url || '',
          consumers: info.consumers || 0,
        });
      }
    } catch (error) {
      logger.error(`Failed to get streams: ${error}`);
    }

    return result;
  }

  // Get WebRTC signaling URL for a stream (HTTP POST endpoint)
  getWebRTCUrl(streamId: string): string {
    return `http://localhost:${this.config.apiPort}/api/webrtc?src=${encodeURIComponent(streamId)}`;
  }

  // Get the API base URL
  getApiUrl(): string {
    return `http://localhost:${this.config.apiPort}`;
  }

  // Get the WebRTC port
  getWebRTCPort(): number {
    return this.config.webrtcPort;
  }
}

// Factory function
export function createGo2RTCService(config: Go2RTCConfig): Go2RTCService {
  return new Go2RTCService(config);
}

export default Go2RTCService;
